name: PrimeHologram
main: nasiridrishi\primehologram\PrimeHologram
src-namespace-prefix: nasiridrishi\primehologram
version: 1.0.0
api: [5.0.0]
author: nasiridrishi
softdepend:
  - PrimePlaceHolder

commands:
  holoreload:
    description: "Realod holograms"
    usage: "/holoreload"
    permission: "prime.holoreload"
permissions:
  prime.holoreload:
    description: "Realod holograms"
    default: op
